from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE

OUT = "it3203-assignment1-http-evolution/IT3203_Assignment1_HTTP_Evolution_Nasir_Hassan.pptx"

slides = [
("HTTP: The Protocol That Carries the Web", ["IT 3203 Assignment 1: Research and Learn Web Evolution", "Prepared by Nasir Hassan • Fall 2026", "Research focus: one web component — Hypertext Transfer Protocol (HTTP). This report explains HTTP's purpose, history, recent development, current status, and future direction."], "Title", "Assignment prompt; MDN; IETF RFC 9110–9114"),
("Executive overview: what this report teaches", ["HTTP is the common language that lets browsers, servers, apps, APIs, and content delivery networks exchange web resources.", "HTTP began as a tiny protocol for requesting one hypertext document. It evolved into a flexible application protocol for documents, media, APIs, streaming, security policies, and web applications.", "The basic request/response meaning stayed stable while the transport improved: HTTP/1.1 emphasized reuse, HTTP/2 added multiplexing, and HTTP/3 moved to QUIC.", "Modern HTTP affects speed, reliability, privacy, and security every time a user loads a page, submits a form, opens a web app, or calls an API."], "Overview", "RFC 9110; RFC 9113; RFC 9114"),
("Research scope and learning goals", ["This report focuses only on HTTP, rather than browsers, HTML, URLs, or web servers.", "Main question: How did HTTP evolve from a simple document-transfer protocol into the modern system that supports secure, high-performance web applications?", "Learning goals include explaining HTTP's role, tracing major versions, understanding methods and status codes, examining HTTPS and caching, comparing performance designs, and evaluating future directions.", "The slides are written as a self-contained learning resource for high school students, so the text explains the ideas without requiring an oral presentation."], "Overview", "IT 3203 Assignment 1 prompt"),
("Where HTTP fits in a web request", ["A browser is the client. A web server or CDN is the service that receives requests and returns responses.", "Before HTTP content moves, DNS usually resolves the domain name and the device creates a network connection. HTTPS also negotiates TLS encryption.", "The browser sends an HTTP request containing a method, target path, headers, and sometimes a body. The server returns a status, headers, and usually a response body.", "HTML describes page structure, CSS controls appearance, and JavaScript controls behavior. HTTP is the delivery and coordination protocol that moves those resources."], "Core Concepts", "RFC 9110; MDN Evolution of HTTP"),
("The request/response pattern", ["A request asks for an action or resource. Example: GET /products.html HTTP/1.1 with Host and Accept headers.", "A response reports the result. Example: HTTP/1.1 200 OK followed by headers such as Content-Type and Cache-Control.", "The body can carry HTML, JSON, CSS, JavaScript, images, video data, or uploaded form content.", "Because the conversation is standardized, browsers and servers from different organizations can communicate without having been designed together."], "Core Concepts", "RFC 9110"),
("HTTP message parts and why they matter", ["The start line identifies the method and target for a request, or the status code for a response.", "Headers are key-value metadata fields. They can describe content type, compression, caching, language, authentication, cookies, cross-origin rules, and security policy.", "A blank line separates the headers from the optional message body.", "HTTP is stateless: each request can be understood independently. Sites add continuity through cookies, sessions, tokens, caches, and databases."], "Core Concepts", "RFC 9110"),
("Important HTTP methods", ["GET retrieves a resource and should not normally change server state.", "POST submits data or asks the server to create or process something, such as a form submission or API request.", "PUT typically replaces a resource, while PATCH changes part of a resource.", "DELETE asks the server to remove a resource. HEAD is similar to GET but requests headers without the response body.", "Methods give web APIs a shared vocabulary for describing what the client wants to do."], "Core Concepts", "RFC 9110"),
("Status codes: software-readable results", ["1xx codes provide informational responses. 2xx codes mean a request succeeded; 200 OK is the most familiar example.", "3xx codes indicate redirection or another location. 301 and 302 are common redirect responses.", "4xx codes indicate a client-side problem, such as 400 Bad Request, 401 Unauthorized, 403 Forbidden, or 404 Not Found.", "5xx codes indicate a server-side failure, such as 500 Internal Server Error or 503 Service Unavailable.", "Status codes allow software to react automatically instead of trying to interpret an error page as ordinary content."], "Core Concepts", "RFC 9110"),
("Origin story: the web needed a protocol", ["In 1989 Tim Berners-Lee proposed a networked hypertext system at CERN. The early World Wide Web combined HTML documents, URLs, a browser, a web server, and HTTP.", "HTTP's job was to exchange web documents. The first design emphasized simplicity because the early web mostly transferred text and hypertext.", "As the web added images, forms, multiple media types, e-commerce, APIs, and rich applications, HTTP gained metadata and performance features.", "The historical lesson is that HTTP stayed useful because it could evolve without changing its central request/response idea."], "History", "W3C Information Management: A Proposal; MDN"),
("HTTP/0.9: the one-line protocol", ["An early request could be as small as GET /index.html.", "The server returned the document directly. There were no response headers, status codes, content types, or standardized error codes.", "Only GET was supported, so the design was focused on retrieving hypertext documents rather than submitting complex data.", "This model became too limited once the web needed images, forms, different content types, caching, and automatic browser behavior."], "History", "MDN Evolution of HTTP"),
("HTTP/1.0: headers made HTTP extensible", ["HTTP/1.0 documented protocol versioning, status codes, headers, and support for different media types.", "Content-Type allowed the response to identify HTML, images, downloads, and other file formats.", "Status codes allowed browsers to distinguish success, redirects, missing files, and server errors.", "Headers created an extension mechanism that later supported caching, cookies, authentication, security policy, compression, and content negotiation."], "History", "RFC 1945; MDN"),
("HTTP/1.1: standardization and reuse", ["HTTP/1.1 became the long-lasting foundation of web communication.", "Persistent connections allowed many requests to reuse one TCP connection instead of repeatedly paying connection-setup cost.", "The Host header made virtual hosting practical by allowing many domain names to share one IP address.", "HTTP/1.1 also clarified caching, content negotiation, range requests, chunked transfer, and other behaviors important to the commercial web."], "History", "RFC 9112; MDN"),
("Caching: avoiding unnecessary downloads", ["A cache stores a previously received response so it may be reused instead of downloaded again.", "Cache-Control can define freshness rules, while ETag and Last-Modified help a browser validate whether a stored copy is still current.", "Effective caching improves page speed and reduces bandwidth use for both users and servers.", "CDNs extend the same idea globally by serving copies from edge locations closer to users."], "HTTP/1.1 Features", "RFC 9111"),
("Content negotiation and compression", ["Clients can advertise acceptable languages, formats, and encodings using request headers.", "Servers can choose an appropriate representation and identify it with response headers.", "Compression such as gzip or Brotli can reduce the number of bytes sent across the network.", "This made HTTP a coordination system for how content should be delivered, not merely a pipe carrying the content."], "HTTP/1.1 Features", "RFC 9110; RFC 9111"),
("Cookies and web sessions", ["HTTP itself is stateless, but cookies allow a server to place small pieces of state in a browser and receive them with later requests.", "Cookies can support login sessions, preferences, shopping carts, and analytics.", "Security attributes such as Secure, HttpOnly, and SameSite help limit how cookies are sent or accessed.", "Because cookies can also be used for tracking, they are an important part of modern privacy and browser policy discussions."], "Applications", "RFC 6265 family; MDN"),
("HTTPS: HTTP protected by TLS", ["Plain HTTP can expose data to interception or modification on an untrusted network.", "HTTPS runs HTTP through TLS. TLS encrypts traffic, helps authenticate the server, and protects message integrity in transit.", "HTTPS is essential for passwords, payment information, authentication cookies, personal messages, and forms.", "Modern browsers increasingly treat HTTPS as the normal expectation for trustworthy sites and reserve important features for secure contexts."], "Security", "RFC 9110; TLS specifications; MDN"),
("HTTP and modern web APIs", ["A web API often uses the same HTTP methods, headers, status codes, and URLs that browsers use.", "JSON is a common API body format because applications can easily convert it into objects and data structures.", "REST-style APIs commonly use GET to read, POST to create or process, PUT/PATCH to update, and DELETE to remove.", "HTTP's broad tool support makes APIs easy to test with browsers, curl, developer tools, gateways, and monitoring systems."], "Applications", "RFC 9110; MDN"),
("The HTTP/1.1 performance problem", ["Modern pages can require HTML, CSS, JavaScript, images, fonts, analytics, API calls, ads, and third-party resources.", "Browsers opened several TCP connections per origin to reduce waiting, but many parallel connections add setup overhead and compete for network capacity.", "HTTP/1.1 pipelining was difficult to deploy because one slow response could delay responses behind it.", "These performance pressures helped motivate a new wire format while preserving HTTP semantics."], "Performance", "MDN Evolution of HTTP"),
("HTTP/2: same meaning, new wire format", ["HTTP/2 kept familiar methods, status codes, headers, URLs, and application semantics.", "It introduced binary framing. Requests and responses are divided into frames associated with streams.", "Multiplexing allows several streams to share one connection instead of requiring a separate connection for each resource.", "HPACK header compression reduces repeated header bytes, which is useful because many requests send similar metadata."], "HTTP/2", "RFC 9113"),
("HTTP/2 multiplexing explained", ["Think of HTTP/1.1 as several checkout lines that may each move at different speeds. HTTP/2 organizes many conversations inside one coordinated connection.", "Frames from different streams can be interleaved, so one application request does not need to fully finish before another starts sending data.", "This reduces the need for domain sharding and other workarounds that websites used to create more parallel connections.", "HTTP/2 improves application-layer concurrency, but it still runs over TCP, whose ordered delivery can cause transport-level blocking when packets are lost."], "HTTP/2", "RFC 9113"),
("Why HTTP/3 uses QUIC", ["HTTP/3 preserves HTTP semantics but runs over QUIC instead of TCP.", "QUIC is built over UDP and includes secure connection setup, multiplexed streams, loss recovery, and connection migration.", "A lost packet affecting one QUIC stream does not automatically block delivery of unrelated streams in the same way TCP's single ordered byte stream can.", "QUIC was designed with encryption from the beginning, so HTTP/3 deployment is closely tied to modern secure networking."], "HTTP/3", "RFC 9000; RFC 9114"),
("Connection migration and mobile networks", ["Phones frequently move between Wi-Fi and cellular networks or change network paths.", "Traditional TCP connections are strongly tied to endpoint addressing, so a path change can require a new connection.", "QUIC uses connection identifiers that can let an established connection survive some address changes.", "This does not eliminate every mobile-network problem, but it is an example of transport design adapting to how people actually use the internet today."], "HTTP/3", "RFC 9000"),
("Comparing HTTP generations", ["HTTP/0.9: extremely simple document retrieval, but no headers or status codes.", "HTTP/1.0: adds metadata, status codes, and content types, but commonly creates many short connections.", "HTTP/1.1: adds durable standardization, persistent connections, caching, and virtual hosting, but still faces ordering and concurrency limits.", "HTTP/2: adds binary framing, multiplexing, and header compression while keeping TCP.", "HTTP/3: keeps HTTP semantics but uses QUIC for secure, multiplexed transport with improved behavior under loss and path changes."], "Comparison", "RFC 9110–9114"),
("Current status: several versions coexist", ["The public web does not switch protocols all at once. HTTP/1.1, HTTP/2, and HTTP/3 can coexist because clients and servers negotiate what they support.", "HTTP/1.1 remains important as a compatibility and fallback protocol.", "HTTP/2 is widely deployed across browsers, web servers, reverse proxies, and CDNs.", "HTTP/3 continues growing as QUIC support becomes common, especially through large browsers, cloud platforms, and content delivery networks."], "Current Status", "W3Techs; browser and CDN documentation"),
("People and organizations behind HTTP", ["Tim Berners-Lee and CERN created the original World Wide Web system in which HTTP first appeared.", "The Internet Engineering Task Force (IETF) develops open internet standards and publishes HTTP specifications as RFCs.", "Browser vendors such as Google, Mozilla, Apple, and Microsoft implement protocol negotiation, security policy, caching, and compatibility behavior.", "Cloud providers, CDNs, server projects, and networking researchers test and deploy HTTP versions at internet scale."], "Ecosystem", "W3C history; IETF HTTP Working Group"),
("Recent developments: HTTP still changes", ["In 2022 the core HTTP standards were reorganized into modern RFCs covering semantics, caching, HTTP/1.1, HTTP/2, and HTTP/3.", "Extensible prioritization work aims to provide simpler signals for deciding which responses or resources should receive attention first.", "103 Early Hints can allow a server to send useful resource hints before the final response is ready.", "Research continues on HTTP/3 security, performance, proxies, loss behavior, and quality of experience, showing that standardization continues after initial deployment."], "Recent Developments", "RFC 9110–9114; RFC 9218; RFC 8297"),
("Future directions after HTTP/3", ["The future is likely to focus more on extending secure, efficient HTTP than on replacing the entire protocol model.", "Encrypted-by-default traffic will continue to shape browser security, enterprise networking, monitoring, and privacy design.", "QUIC-based technologies such as WebTransport and proxy/tunneling work explore uses beyond ordinary page loading.", "Edge computing will keep using HTTP caching, routing, headers, and security policy to move application logic and content closer to users."], "Future", "RFC 9000; RFC 9114; RFC 9218"),
("Challenges and tradeoffs", ["Compatibility matters because new protocol versions must coexist with older clients, servers, proxies, firewalls, and embedded systems.", "Encryption improves user privacy but changes what intermediate network devices can inspect, increasing the importance of endpoint logging and observability.", "HTTP/3 and QUIC introduce new code paths that load balancers, firewalls, CDNs, and servers must implement correctly.", "Performance is contextual: caching, server location, JavaScript weight, image size, and application design can matter as much as the negotiated HTTP version."], "Critical Analysis", "RFC 9110–9114; HTTP/3 research"),
("Security problems HTTP deployments must manage", ["Request smuggling and parsing differences can appear when multiple systems disagree about HTTP message boundaries.", "Cache poisoning can cause incorrect or attacker-controlled content to be stored and delivered to other users.", "Cross-origin mistakes, weak cookie settings, or missing security headers can expose data even when TLS is present.", "Standards reduce risk, but secure operation still requires correct configuration, patching, logging, testing, and application-level security practices."], "Critical Analysis", "OWASP; RFC 9110–9114"),
("Demonstration: inspect HTTP in a browser", ["Open Chrome, Edge, or Firefox Developer Tools and select the Network tab.", "Reload a page and select a request. Inspect the request URL, method, status, request headers, response headers, content type, timing, and protocol information.", "Look for Cache-Control, ETag, Content-Encoding, Set-Cookie, Strict-Transport-Security, and Alt-Svc when available.", "A useful learning activity is to compare a school site, a news site, and a small personal site and record their methods, statuses, cache rules, security headers, and protocol versions."], "Demonstration", "Browser DevTools documentation"),
("Demonstration: inspect HTTP with curl", ["curl is a command-line tool that can send HTTP requests and display responses.", "Example: curl -I https://example.com requests response headers without downloading the full body.", "A curl build with HTTP/3 support can attempt QUIC using options such as --http3.", "Command-line testing helps students see HTTP as a protocol independently from the visual browser interface."], "Demonstration", "curl documentation; RFC 9110; RFC 9114"),
("Conclusion: HTTP is the web's coordination layer", ["HTTP began with a simple GET request for a hypertext document and grew because headers, methods, and status codes made it extensible.", "HTTP/1.1 made web delivery practical at scale with standardization, persistent connections, caching, and virtual hosting.", "HTTP/2 improved concurrency by changing framing and multiplexing while preserving application semantics.", "HTTP/3 moved the protocol over QUIC to address transport-level limitations and modern network behavior.", "HTTP remains successful because the web can keep the same high-level language while improving performance, security, and transport underneath."], "Conclusion", "MDN; RFC 9110–9114"),
("References and good resources (1 of 2)", ["Berners-Lee, T. (1989). Information Management: A Proposal. W3C history archive. https://www.w3.org/History/1989/proposal.html", "MDN Web Docs. Evolution of HTTP. https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Evolution_of_HTTP", "Fielding, Nottingham, & Reschke. RFC 9110: HTTP Semantics. https://datatracker.ietf.org/doc/html/rfc9110", "Fielding, Nottingham, & Reschke. RFC 9111: HTTP Caching. https://datatracker.ietf.org/doc/html/rfc9111", "Fielding, Nottingham, & Reschke. RFC 9112: HTTP/1.1. https://datatracker.ietf.org/doc/html/rfc9112", "Thomson & Benfield. RFC 9113: HTTP/2. https://datatracker.ietf.org/doc/html/rfc9113"], "References", "Primary standards and learning resources"),
("References and good resources (2 of 2)", ["Bishop, M. RFC 9114: HTTP/3. https://datatracker.ietf.org/doc/html/rfc9114", "Iyengar & Thomson. RFC 9000: QUIC. https://datatracker.ietf.org/doc/html/rfc9000", "W3Techs. HTTP/2 and HTTP/3 usage statistics. https://w3techs.com/technologies/overview/web_server", "Cloudflare Blog. HTTP/3: the past, the present, and the future. https://blog.cloudflare.com/http3-the-past-present-and-future/", "Nottingham & Oku. RFC 9218: Extensible Prioritization Scheme for HTTP. https://datatracker.ietf.org/doc/html/rfc9218", "Thomson. RFC 8297: An HTTP Status Code for Indicating Hints. https://datatracker.ietf.org/doc/html/rfc8297", "Chatzoglou et al. HTTP/3 security research. https://arxiv.org/abs/2208.06722"], "References", "Additional current-status and future-direction resources"),
("Appendix: quick glossary", ["Client — program that sends HTTP requests, such as a browser, app, curl, or another server.", "Server — program or service that accepts HTTP requests and sends responses.", "Header — key-value metadata field controlling content type, caching, cookies, security, compression, and more.", "TLS — encryption and authentication technology used by HTTPS.", "CDN — content delivery network that serves content from locations closer to users.", "QUIC — secure UDP-based transport used by HTTP/3.", "Head-of-line blocking — delay in which one stalled item prevents later items from progressing.", "API — application programming interface; many modern APIs use HTTP methods, headers, status codes, and JSON bodies."], "Appendix", "RFC 9110; RFC 9114; MDN")
]

prs = Presentation()
prs.slide_width = Inches(13.333333)
prs.slide_height = Inches(7.5)
blank = prs.slide_layouts[6]
NAVY = RGBColor(11,31,51)
BLUE = RGBColor(31,111,235)
TEXT = RGBColor(31,41,55)
MUTED = RGBColor(100,116,139)
LIGHT = RGBColor(244,247,251)
WHITE = RGBColor(255,255,255)

for idx, (title, body, section, source) in enumerate(slides, 1):
    s = prs.slides.add_slide(blank)
    bg = s.background.fill
    bg.solid(); bg.fore_color.rgb = WHITE

    if idx == 1:
        band = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height)
        band.fill.solid(); band.fill.fore_color.rgb = NAVY; band.line.fill.background()
        tb = s.shapes.add_textbox(Inches(0.8), Inches(1.15), Inches(11.8), Inches(1.4))
        p = tb.text_frame.paragraphs[0]; p.text = title; p.font.size = Pt(34); p.font.bold = True; p.font.color.rgb = WHITE
        p.alignment = PP_ALIGN.CENTER
        y = 3.0
        for line in body:
            box = s.shapes.add_textbox(Inches(1.25), Inches(y), Inches(10.8), Inches(0.55))
            q = box.text_frame.paragraphs[0]; q.text = line; q.font.size = Pt(17 if y < 4 else 14); q.font.color.rgb = RGBColor(220,235,255); q.alignment = PP_ALIGN.CENTER
            y += 0.72
        continue

    header = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, Inches(0.72))
    header.fill.solid(); header.fill.fore_color.rgb = NAVY; header.line.fill.background()
    sec = s.shapes.add_textbox(Inches(0.45), Inches(0.17), Inches(3.2), Inches(0.32))
    p = sec.text_frame.paragraphs[0]; p.text = section; p.font.size = Pt(11); p.font.bold = True; p.font.color.rgb = RGBColor(190,220,255)
    num = s.shapes.add_textbox(Inches(11.7), Inches(0.17), Inches(1.0), Inches(0.32))
    p = num.text_frame.paragraphs[0]; p.text = f"{idx:02d}"; p.font.size = Pt(11); p.font.color.rgb = WHITE; p.alignment = PP_ALIGN.RIGHT

    title_box = s.shapes.add_textbox(Inches(0.7), Inches(0.95), Inches(11.9), Inches(0.72))
    p = title_box.text_frame.paragraphs[0]; p.text = title; p.font.size = Pt(25); p.font.bold = True; p.font.color.rgb = NAVY

    accent = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.7), Inches(1.72), Inches(1.15), Inches(0.06))
    accent.fill.solid(); accent.fill.fore_color.rgb = BLUE; accent.line.fill.background()

    body_box = s.shapes.add_textbox(Inches(0.8), Inches(1.95), Inches(11.75), Inches(4.78))
    tf = body_box.text_frame; tf.word_wrap = True; tf.margin_left = Inches(0.08); tf.margin_right = Inches(0.08); tf.vertical_anchor = MSO_ANCHOR.TOP
    total_chars = sum(len(x) for x in body)
    fs = 15
    if total_chars > 1150: fs = 13
    elif total_chars > 850: fs = 14
    for j, item in enumerate(body):
        p = tf.paragraphs[0] if j == 0 else tf.add_paragraph()
        p.text = item; p.font.size = Pt(fs); p.font.color.rgb = TEXT; p.space_after = Pt(7); p.level = 0
        p.text = "• " + p.text

    foot = s.shapes.add_textbox(Inches(0.75), Inches(6.93), Inches(11.8), Inches(0.28))
    p = foot.text_frame.paragraphs[0]; p.text = f"Sources: {source}"; p.font.size = Pt(8.5); p.font.color.rgb = MUTED

prs.save(OUT)
print(OUT)
